#! /bin/bash

G='\033[0;32m'
LG='\033[1;32m'
Y='\033[1;33m'
US443='TCP/vpnbook-us178-tcp443.ovpn'
US80='TCP/vpnbook-us178-tcp80.ovpn'
PL443='TCP/vpnbook-pl140-tcp443.ovpn'
PL80='TCP/vpnbook-pl140-tcp80.ovpn'

clear

tput cup 2 0

echo -e	"${Y}	██╗   ██╗██████╗ ███╗   ██╗    ███████╗███████╗██╗        " 
echo -e	"${Y}	██║   ██║██╔══██╗████╗  ██║    ██╔════╝██╔════╝██║        " 
echo -e	"${Y}	██║   ██║██████╔╝██╔██╗ ██║    ███████╗█████╗  ██║        " 
echo -e	"${Y}	╚██╗ ██╔╝██╔═══╝ ██║╚██╗██║    ╚════██║██╔══╝  ██║        "
echo -e	"${Y}	 ╚████╔╝ ██║     ██║ ╚████║    ███████║███████╗███████╗   " 
echo -e	"${Y}	  ╚═══╝  ╚═╝     ╚═╝  ╚═══╝    ╚══════╝╚══════╝╚══════╝ \n"    
                                                           
echo -e "             ${G}PLEASE SELECT AN OPENVPN VPN CONFIGURATION:${LG}  \n"
echo -e "              .----.--------------------------------.═╗       "
echo -e "              | 1. |         US VPN:443             | ║       "
echo -e "              :----+--------------------------------: ║       "
echo -e "              | 2. |         US VPN:80              | ║       "
echo -e "              :----+--------------------------------: ║       "
echo -e "              | 3. |         PL VPN:443             | ║       "
echo -e "              :----+--------------------------------: ║       "
echo -e "              | 4. |         PL VPN:80              | ║       "
echo -e "              :----+--------------------------------: ║       "
echo -e "              | 5. |         EXIT                   | ║       "
echo -e "              '----'--------------------------------' ║       "
echo -e "              ╚═══════════════════════════════════════╝   ${Y}"

VPNConfig=""

while [[ $VPNConfig = "" ]]; do

read -p "                => " selection

case $selection in
[1]) 
VPNConfig=$US443;;

[2]) 
VPNConfig=$US80;;

[3]) 
VPNConfig=$PL443;;
[4]) 
VPNConfig=$PL443;;
[5])
clear
exit 1;;
[6-9,0])
echo -e "\n                Please select an option!";;
esac

done

Yay=""

while [[ $Yay = "" ]]; do
echo -e "                Do you wanna use: $VPNConfig? Y/N"

read -p "                => " yn

case $yn in
[Y,y])
echo "                   Okay sounds good!"
Yay=1;;
[N,n])
echo "                   Exiting..."
exit 1;;
esac

done

echo "                   Starting VPN..."

sudo openvpn --config $VPNConfig --auth-user-pass pass.txt
